### ISSUE TITLE
where to download 

### ISSUE THREAD

**Issue by stsaih** [xunchen85/VIcaller#6]
Hi,

We would like to try VIcaller. However, there is no virus files  for download from website "www.uvm.edu/genomics/software/VIcaller.html"

This is the statement from page 4 of the VIcaller  User Manual :
"Obtain and index the virome-wide library using BWA, Bowtie2, and BLAST+ separately:
a) Download the virus_db_090217.fa, virus_db_090217.taxonomy, virus_db_090217.virus_list
and Vector.fa files from the website: www.uvm.edu/genomics/software/VIcaller.html"

Could you let us know where to download those ? 

Thanks,
Sharon

**Comment by xunchen85** [comment]
Hi Sharon,

Due to the size limitation, we cannot keep our full version of VIcaller including the virome-wide database on github. To get the library, you can download the VIcaller Version 1.1 from the link www.uvm.edu/genomics/software/VIcaller.html. Then you will find the virome-wide library under the  Database/ folder. 

PS: I would suggest you using the scripts on github which is well maintained.

Let me know if you still cannot get it.

Best,
Xun

**Comment by stsaih** [comment]
Hi Xun, 

Our IT followed your instruction to download the VIcaller Version 1.1 from the link above and found the virome-wide library.  Thank you very much!

Best,
Sharon
